name: fmt

on: [push, pull_request]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Aptos CLI
        run: |
          curl -fsSL "https://aptos.dev/scripts/install_cli.py" | python3
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Format Check
        run: |
          aptos move fmt
          git diff --exit-code
